export const data = [
  {
    _id: "6106da161d773fc5783bd589",
    picture: "http://placehold.it/32x32",
    age: 23,
    name: "Celina Dickson",
    gender: "female",
    company: "GEEKFARM",
    email: "celinadickson@geekfarm.com",
    phone: "+1 (845) 474-2309",
    address: "810 Hull Street, Delwood, Idaho, 6477",
    about:
      "Cupidatat sint reprehenderit cillum in enim culpa. Adipisicing labore officia nulla fugiat veniam aliqua adipisicing ea voluptate. Elit irure aliqua voluptate tempor culpa tempor ut ea dolor. Aute minim amet proident anim exercitation deserunt qui exercitation amet qui non deserunt cillum consectetur. Excepteur aliqua eu nisi proident. Culpa ullamco commodo laboris dolor ex consectetur anim ex.\r\n",
  },
  {
    _id: "6106da16f996981065cebf09",
    picture: "http://placehold.it/32x32",
    age: 24,
    name: "Dena Hodges",
    gender: "female",
    company: "ZEROLOGY",
    email: "denahodges@zerology.com",
    phone: "+1 (858) 528-2767",
    address: "451 Russell Street, Tecolotito, Delaware, 118",
    about:
      "Sunt labore ad non duis dolor dolore incididunt commodo do ipsum excepteur quis ut. Eu deserunt officia minim quis. Velit non excepteur officia incididunt. In nisi consequat nulla aliqua mollit qui do sunt ullamco. Dolore reprehenderit sunt ex dolor ipsum pariatur sunt eu consequat aliqua commodo laborum do.\r\n",
  },
  {
    _id: "6106da167ce119151aeefcab",
    picture: "http://placehold.it/32x32",
    age: 30,
    name: "Kasey Stein",
    gender: "female",
    company: "CALCU",
    email: "kaseystein@calcu.com",
    phone: "+1 (865) 508-2114",
    address: "448 Fleet Walk, Richmond, Mississippi, 2920",
    about:
      "Commodo tempor eiusmod commodo pariatur exercitation irure velit et. Sit dolor voluptate minim ad occaecat aliqua ad id aliquip adipisicing nisi cupidatat ea. Aute ex occaecat id anim. Pariatur laborum commodo dolore ipsum incididunt ullamco voluptate esse commodo do adipisicing officia culpa aliqua. Anim labore consequat id aliqua laboris ipsum. Fugiat ex deserunt est do.\r\n",
  },
  {
    _id: "6106da164c5778bcc08e418a",
    picture: "http://placehold.it/32x32",
    age: 21,
    name: "Garza Goodwin",
    gender: "male",
    company: "AQUASURE",
    email: "garzagoodwin@aquasure.com",
    phone: "+1 (800) 444-2130",
    address: "383 Elliott Walk, Rodanthe, South Carolina, 4350",
    about:
      "Voluptate laboris labore nulla aliquip voluptate exercitation reprehenderit incididunt minim. Irure excepteur elit esse veniam labore et sunt et nulla. Excepteur cupidatat incididunt amet dolor deserunt sint veniam sunt pariatur nostrud occaecat deserunt. Aliquip officia Lorem duis aliquip aliqua. Nisi esse sunt velit aute Lorem reprehenderit esse minim dolor et ipsum exercitation incididunt non. Exercitation elit nostrud laboris excepteur consectetur exercitation consectetur cillum proident et exercitation id.\r\n",
  },
  {
    _id: "6106da161dff5ad6f4ed342c",
    picture: "http://placehold.it/32x32",
    age: 25,
    name: "Brady Bird",
    gender: "male",
    company: "EXOVENT",
    email: "bradybird@exovent.com",
    phone: "+1 (845) 578-3660",
    address: "362 Ocean Parkway, Durham, Puerto Rico, 1408",
    about:
      "Commodo sint enim ad esse. Ad culpa occaecat velit commodo do veniam labore ipsum aute id occaecat dolore. Consequat enim labore deserunt amet pariatur est cillum occaecat ut. Sunt eu qui sit tempor ad. Enim est amet non in excepteur id consequat laborum non veniam. Qui nulla velit qui ipsum proident esse amet labore dolore occaecat exercitation ipsum cupidatat. Laborum laboris nisi ipsum veniam ea et nulla consequat sit duis ea magna.\r\n",
  },
  {
    _id: "6106da16e7015c480fd95fd1",
    picture: "http://placehold.it/32x32",
    age: 20,
    name: "Taylor Becker",
    gender: "female",
    company: "NETERIA",
    email: "taylorbecker@neteria.com",
    phone: "+1 (996) 421-3033",
    address: "505 Turnbull Avenue, Shrewsbury, Maine, 5115",
    about:
      "Cillum ea esse excepteur minim sunt ex adipisicing labore nulla enim eiusmod duis ullamco. Ut excepteur nisi occaecat voluptate in et. Sunt sint nisi ad eu non elit esse Lorem. Anim in nisi ex aute dolore eiusmod labore sit cupidatat laboris ipsum. Est consectetur ex exercitation consectetur elit sunt veniam. Occaecat nisi id sint excepteur enim. Enim culpa dolor ullamco proident sint Lorem occaecat id laboris eu nisi cupidatat.\r\n",
  },
  {
    _id: "6106da164eedfa1bcd876e4d",
    picture: "http://placehold.it/32x32",
    age: 36,
    name: "Rosemary Bond",
    gender: "female",
    company: "SNORUS",
    email: "rosemarybond@snorus.com",
    phone: "+1 (883) 510-3994",
    address: "320 Noel Avenue, Kerby, North Carolina, 9646",
    about:
      "Proident cillum magna officia sit do adipisicing eu minim sit qui. Ex proident incididunt exercitation aute veniam ea proident veniam proident irure minim mollit. Cupidatat sunt esse consectetur incididunt velit do Lorem elit eu deserunt. Aliquip excepteur duis ullamco nulla laboris ipsum nulla Lorem irure deserunt. Excepteur minim Lorem anim aute ad nisi nostrud aute nisi laborum amet. Aliquip sunt nisi eiusmod veniam dolore ea. Consectetur mollit commodo voluptate voluptate voluptate commodo elit occaecat do deserunt.\r\n",
  },
];
